Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Layout/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 1000
Metrics/ClassLength:
  Exclude:
    - "path/to/your/file.rb"
Metrics/BlockLength:
  Exclude:
    - "path/to/your/file.rb"
Metrics/BlockLength:
  Max: 100
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'
Style/InverseMethods:
  Exclude:
    - 'bin/yarn'
